name: "Twingate Connector"
version: "1.0.0"
slug: "twingate_connector"
description: "A Home Assistant add-on to run the Twingate Connector for secure remote access."
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
options:
  twingate_network: "your_network_name_here"
  twingate_access_token: "your_access_token_here"
  twingate_refresh_token: "your_refresh_token_here"
schema:
  twingate_network: str
  twingate_access_token: str
  twingate_refresh_token: str
