name: "Twingate Connector"
version: "1.0.1"
slug: "twingate_connector"
description: "A Home Assistant add-on to run the Twingate Connector for secure remote access."
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
options:
  twingate_network: ""
  twingate_access_token: ""
  twingate_refresh_token: ""
schema:
  twingate_network: str
  twingate_access_token: str
  twingate_refresh_token: str
